# -*- coding: utf-8 -*-
"""Normalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oc_cQn9X4weikQwaHeu_KZtlLcYS5MM1
"""

text='There were once Three little pigs!They lived in a straw hut,a stick hut,and a brick hut'
normalized_text=text.lower()
normalized_text="".join([char for char in normalized_text if char.isalnum() or char.isspace()])
normalized_text="".join(normalized_text.split())
print("Original text:",text)
print("Normalized Text:",normalized_text)

