# -*- coding: utf-8 -*-
"""pos_tags.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lxyy1jqCJP7fCGOYgDAjKMZDvVc_0Jbe
"""

import nltk
from nltk.tokenize import word_tokenize

# Download required resources
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt_tab') # Added download for punkt_tab

# Input text
text = "The quick brown fox jumps over the lazy dog"

# Tokenize
words = word_tokenize(text)

# POS tagging
pos_tags = nltk.pos_tag(words, tagset=None, lang='eng')

print(pos_tags)