# -*- coding: utf-8 -*-
"""spacy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c8r52dSTWggRrHHVxYuU1Q2XQrziy3D5
"""



import spacy
text="The baby is walking it's first move"
nlp=spacy.load('en_core_web_sm')
doc=nlp(text)
for token in doc:
    print(token.text,token.pos_)

