# -*- coding: utf-8 -*-
"""stemming_lemmatize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FhhYeCrKy1oK_rOpYb6Rjd-g2JFGiKGE
"""

import nltk
from nltk.stem import PorterStemmer,WordNetLemmatizer
nltk.download('punkt')
nltk.download('wordnet')
text='The cats were running and studying'
stemmer=PorterStemmer()
stemmer_words=[stemmer.stem(word=word) for word in text.split()]
print(stemmer_words)
lemmatizer=WordNetLemmatizer()
lemmatizer_words=[lemmatizer.lemmatize(word=word,pos='v') for word in text.split()]
print(lemmatizer_words)

