# -*- coding: utf-8 -*-
"""Textblob.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c8r52dSTWggRrHHVxYuU1Q2XQrziy3D5
"""

!python -m textblob.download_corpora
from textblob import TextBlob
text="The baby is walking"
blob=TextBlob(text)
for word,pos in blob.tags:
    print(word,pos)
